### PR TITLE
Orientation method for getting dim-names from affine (#55)

### PR DESCRIPTION
**Pull request by Tokazama**
@dale-black

Still need to put together the actual tests for this, but the `orientation` method should resolve this.

### CODE REVIEW

**Comment by Dale-Black** [comment]
This [repo](https://github.com/Dale-Black/DICOMUtils.jl) is super messy but it might have some useful functions. I have ported a handful of the functions from nibabel [specifically](https://github.com/nipy/nibabel/blob/master/nibabel/orientations.py) and I am trying to get these to work with both DICOM and NIfTI files

**Comment by Tokazama** [comment]
@Dale-Black, I agree that those nibabel functions look useful but the largest benefit of using Julia is that we can ultimately rely on something like Images.jl to reorient stuff. I've allowed myself to become endlessly sidetracked with other work projects, but hope to make some serious progress next week on improving that interface.

At the very least does this address your original issue, concerning retrieving the dimension names?

**Comment by Tokazama** [comment]
Unless there's any objections I'm gonna go ahead and merge this. I looked at several libraries (including the original NIfTI code) to develop this and it passes basic tests, so it should at least be accurate.

**Comment by Dale-Black** [comment]
Yeah, this all looks really good. I need to familiarize myself with the broader Images.jl libraries to get a better understanding of how to take advantage of Julia's composability in this circumstance

**Pull request merged**
