### PR TITLE
Add support for NIfTI2 header

### PR DESCRIPTION
**Pull request by calvinchai**

### CODE REVIEW

**Comment by calvinchai** [comment]
#69

**Comment by Tokazama** [comment]
Similar to the other PR. This one especially needs tests. Since NIFTI2 isn't always used the same way as NIFTI1, we need to make sure that we carefully test that we are reading the correct bytes into each field. Although we'd like to ultimately ensure we can read all canonical field variants correctly in our tests, this requires some extra decision making on how to handle things like "intent" fields as a public API. For now an empty image with a header that we know is correct would be sufficient.

I know this is a good chunk of extra work but it will help us ensure we don't accidentally break your pipeline down the road unexpectedly.

**Comment by calvinchai** [comment]
Hi, I have added the basic test to read and write the nifti2 file. Is there anything you want specifically to test further?

**Comment by calvinchai** [comment]
Currently, the existing tests all pass so I think it does not break anything that exists already. I also added two lines to read and write a NIfTI-2 file to make sure no error exists.

**Comment by calvinchai** [comment]
Hello @Tokazama, is there any update on this?

**Comment by Tokazama** [comment]
Apologies for the wait. The last thing we need is a version bump to 0.6.1 in the Project.toml file. Then I can send out a release.

**Pull request merged**
